apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- count: 2
  name: vote-ui
patches:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "0"
  target:
    group: apps
    kind: Deployment
    name: vote-api
    version: v1
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "1"
  target:
    kind: Service
    name: vote-api
    version: v1
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "2"
  target:
    group: apps
    kind: Deployment
    name: vote-ui
    version: v1
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "3"
  target:
    kind: Service
    name: vote-ui
    version: v1
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "4"
  target:
    kind: Route
    name: vote-ui
    version: v1
resources:
- ../../k8s/
images:
- digest: sha256:d4117ae4825c488627a1f0612f083bd63a8b6de64b5b5687d5521a5b0622fc90
  name: quay.io/sureshgaikwad/vote-ui:latest
  newName: quay.io/sureshgaikwad/prod-vote-ui
